image: ubuntu

test:
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip
    - apt-get install -y libsndfile1-dev
    - pip3 install -r ./python/requirements.txt
    - chown $USER:$USER python/*
    - python3 -m unittest discover -v -s ./test -p '*test*.py'
